### ISSUE TITLE
cannot add caldav account (errors from: dav/dav.js)

### ISSUE THREAD

**Issue by rwp0** [himselfv/tasks-ig#2]
i cannot add a caldav account,
a message with illegible white foreground text pops up (`dav/dav.js` is somewhat readable) with `ok` button `to prevent this page from creating additional dialogues`
_(a good opportunity to ask for a dark theme compatible with other sidebars if browser theme is dark)_

inspecting extension through `about:debugging` revealas following in the console:

### index.js:891:11
```
Setting up backend
BackendDav() length: 0
​name: "BackendDav"
​prototype: Object { constructor: BackendDav(), connect: connect(), settingsPage: settingsPage(), … }
uiName: "CalDAV"
```

### index.js:324:11
`Initializing backend: BackendDav`

### utils.js:161:17
`script load already failed: davjs`

### backendDav.js:43:13
```
dav: insertDavAPIs error: dav/dav.js: SyntaxError: import declarations may only appear at top level of a module`
```

### index.js:922:13
```
Could not configure backend: dav/dav.js: SyntaxError: import declarations may only appear at top level of a module
```

---
firefox version: `82.0.3`

thank you, it seems to be a useful useful extension

**Comment by himselfv** [comment]
Thanks! Fixed, I hope; please try 1.1.5 (https://addons.mozilla.org/en-US/firefox/addon/tasks-ig/)

**Comment by rwp0** [comment]
thanks, now I can access `caldav settings` menu, but i'm getting unreadable pop-up, and console message (debugging) adding a server ([disroot cloud](https://cloud.disroot.org/)):

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://cloud.disroot.org/remote.php/dav. (Reason: CORS request did not succeed).
```

### index.js:908:17
```
Backend.setup() error: Error: Bad status: 0
    onreadystatechange moz-extension://523c5ba3-1190-4063-b9b0-d1f73c3b055b/dav/dav.js:1
```

---

`server` (input field):
`https://cloud.disroot.org/remote.php/dav`

trivia: i set up [tbsync](https://addons.thunderbird.net/en-US/thunderbird/addon/dav-4-tbsync/) (thunderbird) using this _dav server root uri_

**Comment by himselfv** [comment]
This is probably Disroot/Nextcloud [not configuring CORS](https://github.com/nextcloud/server/issues/3131). [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) is a dubious security measure where a server must explicitly say "yes, I'm okay with other domains" before browsers will even let code from other domains call it.

[Here's my explanation](https://github.com/himselfv/tasks-ig/blob/master/docs/hosting.md#cors). [Here's another DAV JS client talking about it](https://github.com/perry-mitchell/webdav-client#cors).

Two ways to fix it is 1. to edit .htaccess on a server and add CORS headers ([here's an example](https://github.com/himselfv/tasks-ig/blob/master/docs/hosting-cors-htaccess-example.txt)), or 2. to host tasks-ig on the same domain as your DAV.
